{{- if .Values.mongodb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "datashield.mongodb.name" . }}
  labels:
    {{- include "datashield.mongodb.labels" . | nindent 4 }}
  {{- with .Values.mongodb.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.mongodb.service.type }}
  ports:
    - name: mongodb
      port: {{ .Values.mongodb.service.port }}
      targetPort: mongodb
      protocol: TCP
  selector:
    {{- include "datashield.mongodb.selectorLabels" . | nindent 4 }}
{{- end }}
