{{ if .Values.mongodb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "datashield.mongodb.name" . }}
  labels:
    app: {{ include "datashield.mongodb.name" . }}
spec:
  ports:
    - name: tcp
      port: 27017    
      targetPort: 27017
  selector:
    app: {{ include "datashield.mongodb.name" . }}
{{ end }}
