{{ if .Values.mysqldb.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "datashield.mysqldb.name" . }}
  labels:
    app: {{ include "datashield.mysqldb.name" . }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.mysqldb.pvc.storage | quote }}
{{ end }}