{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "datashield.mysql.name" . }}
  labels:
    {{- include "datashield.mysql.labels" . | nindent 4 }}
  {{- with .Values.mysql.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.mysql.service.type }}
  ports:
    - name: mysql
      port: {{ .Values.mysql.service.port }}
      targetPort: mysql
      protocol: TCP
  selector:
    {{- include "datashield.mysql.selectorLabels" . | nindent 4 }}
{{- end }}