apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  name: {{ include "datashield.mica.name" . }}
  labels:
    app: {{ include "datashield.mica.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "datashield.mica.name" . }}
    strategy: {}
  template:
    metadata:
      annotations: {}
      labels:
        app: {{ include "datashield.mica.name" . }}
    spec:
      containers:
        - image: obiba/mica:5.3
          name: mica
          resources: {}
          # command: ["/bin/bash"]
          # args:
          #   - "-c"
          #   - "while true; do echo hello; sleep 10;done"
            # - "chown -R mica $MICA_HOME; exec gosu mica /opt/mica/bin/start.sh"
          env:
            - name: JAVA_OPTS
              value: -Xmx2G
            - name: MICA_ADMINISTRATOR_PASSWORD
              value: P@55w0rd
            - name: MONGO_HOST
              value: mongo
            - name: MONGO_PORT
              value: "27017"
            - name: OPAL_URL
              value: http://opal:8080
            - name: AGATE_URL
              value: http://agate:8081
      restartPolicy: Always
