{{- if or .Values.mongodb.enabled .Values.mysql.enabled .Values.opal.enabled .Values.rock.enabled .Values.agate.enabled .Values.mica.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "datashield.secretName" . }}
  labels:
    {{- include "datashield.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.mongodb.enabled }}
  {{- if .Values.mongodb.auth.enabled }}
  mongodb-root-password: {{ .Values.mongodb.auth.rootPassword | b64enc }}
  {{- if .Values.mongodb.auth.username }}
  mongodb-username: {{ .Values.mongodb.auth.username | b64enc }}
  mongodb-password: {{ .Values.mongodb.auth.password | b64enc }}
  mongodb-database: {{ .Values.mongodb.auth.database | b64enc }}
  {{- end }}
  {{- end }}
  {{- end }}
  
  {{- if .Values.mysql.enabled }}
  mysql-root-password: {{ .Values.mysql.auth.rootPassword | b64enc }}
  mysql-username: {{ .Values.mysql.auth.username | b64enc }}
  mysql-password: {{ .Values.mysql.auth.password | b64enc }}
  mysql-database: {{ .Values.mysql.auth.database | b64enc }}
  {{- end }}
  
  {{- if .Values.opal.enabled }}
  opal-administrator-password: {{ .Values.opal.config.administratorPassword | b64enc }}
  {{- if .Values.opal.demo.enabled }}
  opal-demo-user-password: {{ .Values.opal.demo.userPassword | b64enc }}
  {{- end }}
  {{- end }}
  
  {{- if .Values.rock.enabled }}
  rock-administrator-password: {{ .Values.rock.config.administratorPassword | b64enc }}
  rock-manager-password: {{ .Values.rock.config.managerPassword | b64enc }}
  rock-user-password: {{ .Values.rock.config.userPassword | b64enc }}
  {{- end }}
  
  {{- if .Values.agate.enabled }}
  agate-administrator-password: {{ .Values.agate.config.administratorPassword | b64enc }}
  {{- end }}
  
  {{- if .Values.mica.enabled }}
  mica-administrator-password: {{ .Values.mica.config.administratorPassword | b64enc }}
  {{- end }}
{{- end }}
