apiVersion: v1
kind: Service
metadata:
  name: {{ include "datashield.opal.name" . }}
  labels:
    app: {{ include "datashield.opal.name" . }}
spec:
  type: {{ .Values.opal.service.type }}
  ports:
    - name: opal
      port: 80 # {{ .Values.opal.service.port }}
      targetPort: 8080
  selector:
    app: {{ include "datashield.opal.name" . }}