apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "datashield.opal.name" . }}
  labels:
    app: {{ include "datashield.opal.name" . }}
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.opal.pvc.storage }}
  # volumeName: {{ include "datashield.opal.name" . }}
  