apiVersion: v1
kind: ConfigMap
metadata:
  name: opal-demo-configmap
data:
  opal-demo-customisation.sh: |-
    #!/usr/bin/env bash

    # This script is run by the opal container on startup.
    # There are some values which are set as ENV VARS in the container which are set in opal-deployment.yaml
    # The rest come from the values.yaml file.

    # https://opaldoc.obiba.org/en/latest/python-user-guide/index.html

    touch /doing_local_customisation.txt

    # Check opal python client is installed
    whereis opal

    echo "Check opal has started before trying to add data etc"
    until opal system --user administrator --password $OPAL_ADMINISTRATOR_PASSWORD --version
    do
      echo "Opal not up yet, sleeping..."
      sleep 5
    done


    # Most of these will just default to localhost

    # Get the verion of opal
    echo "Opal version:"
    opal system --user administrator --password $OPAL_ADMINISTRATOR_PASSWORD --version

    # Add the NORMAL DEMO_USER as defined in the values.yaml
    opal user --user administrator --password $OPAL_ADMINISTRATOR_PASSWORD --add --name {{ .Values.opal.demo.OPAL_DEMO_USER_NAME }} --upassword {{ .Values.opal.demo.OPAL_DEMO_USER_PASSWORD }}
    
    ###########################################################################
    # CNSIM DEMO DATA
    ###########################################################################

    # Add a project
    opal project --user administrator --password $OPAL_ADMINISTRATOR_PASSWORD --add --name {{ .Values.opal.demo.OPAL_DEMO_PROJECT }} --database mongodb

    # Add the CNSIM1 data to the project
    cd /tmp
    mkdir opal-config-temp
    cd opal-config-temp
    wget {{ .Values.opal.demo.OPAL_DEMO_SOURCE_DATA_URL }}

    opal_fs_path="/home/administrator"
    opal_file_path="$opal_fs_path/`basename {{ .Values.opal.demo.OPAL_DEMO_SOURCE_DATA_URL }}`"

    opal file --user administrator --password $OPAL_ADMINISTRATOR_PASSWORD -up `basename {{ .Values.opal.demo.OPAL_DEMO_SOURCE_DATA_URL }}` $opal_fs_path

    opal import-csv --user administrator --password $OPAL_ADMINISTRATOR_PASSWORD --destination {{ .Values.opal.demo.OPAL_DEMO_PROJECT }} --path $opal_file_path  --tables {{ .Values.opal.demo.OPAL_DEMO_TABLE }} --separator , --type Participant --valueType decimal


    ###########################################################################
    # Eunomia OMOP Data
    ###########################################################################

    # Create new project
    opal project --user administrator --password $OPAL_ADMINISTRATOR_PASSWORD --add --name EUNOMIA --database mongodb

    # Add data
    cd /tmp
    wget "https://raw.githubusercontent.com/OHDSI/EunomiaDatasets/main/datasets/Synthea27Nj/Synthea27Nj_5.4.zip"
    unzip Synthea27Nj_5.4.zip -d eunomia
    cd eunomia
    opal_fs_path="/home/administrator/eunomia"
    mkdir -p $opal_fs_path
    for filename in ./*.csv; do 
      fname=$(basename $filename .csv);
      opal_file_path="$opal_fs_path/$fname.csv"

      # Copy the file into the user filesystem      
      cp $fname.csv $opal_fs_path
      # opal file --user administrator --password $OPAL_ADMINISTRATOR_PASSWORD -up $fname.csv $opal_fs_path\$fname.csv
      
      # Import CSV files as tables
      opal import-csv --user administrator --password $OPAL_ADMINISTRATOR_PASSWORD --destination EUNOMIA --path $opal_file_path  --tables $fname --separator , --type $fname
    done

    # Delete the files
    cd ..
    rm -rf eunomia
    rm Synthea27Nj_5.4.zip

    touch /finished_local_customisation.txt