apiVersion: v1
kind: Service
metadata:
  name: opal-service
  labels:
    name: opal-service
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.opal.service.type }}
  ports:
    - name: opal
      port: {{ .Values.opal.service.port }}
      targetPort: 8080
  selector:
    app: {{ template "opal.name" . }}
    release: {{ .Release.Name }}