apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "datashield.mongodb.name" . }}
  labels:
    app: {{ include "datashield.mongodb.name" . }}
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage:  {{ .Values.mongodb.pvc.storage | quote }}
  # volumeName: {{ include "datashield.mongodb.name" . }}
