{{ if .Values.mysqldb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "datashield.mysqldb.name" . }}
  labels:
    app: {{ include "datashield.mysqldb.name" . }}
spec:
  ports:
    - name: tcp
      port: 3306    
      targetPort: 3306
  selector:
    app: {{ include "datashield.mysqldb.name" . }}
{{ end }}