apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "datashield.mysqldb.name" . }}
  labels:
    name: {{ include "datashield.mysqldb.name" . }}
spec:
  storageClassName: default
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.mysqldb.pvc.storage | quote }}
  volumeName: {{ include "datashield.mysqldb.name" . }}
