apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  name: {{ include "datashield.rock.name" . }}
  labels:
    app: {{ include "datashield.rock.name" . }}
spec:
  replicas: {{ .Values.rock.replicatCount }}
  selector:
    matchLabels:
      app: {{ include "datashield.rock.name" . }}
  
  template:
    metadata:
      labels:
        app: {{ include "datashield.rock.name" . }}
    spec:
      containers:
        - name: rock
          image: {{ .Values.rock.image }}
          ports:
            - containerPort: 8085

