apiVersion: v1
kind: Service
metadata:
  name: {{ include "datashield.rock.name" . }}
  labels:
    app: {{ include "datashield.rock.name" . }}
spec:
  ports:
    - name: tcp
      port: 8085
      targetPort: 8085
  selector:
    app: {{ include "datashield.rock.name" . }}
