{{- if and .Values.opal.enabled .Values.opal.persistence.enabled false }}
{{/* 
This PVC is no longer used since OPAL is now a StatefulSet with volumeClaimTemplates.
This file is kept for backwards compatibility but is disabled.
The StatefulSet manages its own PVCs through volumeClaimTemplates.
*/}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "datashield.opal.name" . }}
  labels:
    {{- include "datashield.opal.labels" . | nindent 4 }}
  {{- with .Values.opal.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.opal.persistence.accessMode | quote }}
  {{- if .Values.global.storageClass }}
  storageClassName: {{ .Values.global.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.opal.persistence.size | quote }}
{{- end }}
  