{{- if .Values.opal.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "datashield.opal.name" . }}
  labels:
    {{- include "datashield.opal.labels" . | nindent 4 }}
  {{- with .Values.opal.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.opal.service.type }}
  ports:
    - name: http
      port: {{ .Values.opal.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "datashield.opal.selectorLabels" . | nindent 4 }}
{{- end }}