{{- if and .Values.opal.enabled .Values.opal.demo.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "datashield.opal.name" . }}-demo-config
  labels:
    {{- include "datashield.opal.labels" . | nindent 4 }}
data:
  opal-demo-customisation.sh: |-
    #!/usr/bin/env bash

    # This script is run by the opal container on startup.
    # There are some values which are set as ENV VARS in the container which are set in opal-deployment.yaml
    # The rest come from the values.yaml file.

    # https://opaldoc.obiba.org/en/latest/python-user-guide/index.html

    touch /doing_local_customisation.txt

    # Check opal python client is installed
    whereis opal

    echo "Check opal has started before trying to add data etc"
    until opal system --user administrator --password $OPAL_ADMINISTRATOR_PASSWORD --version
    do
      echo "Opal not up yet, sleeping..."
      sleep 5
    done

    # Most of these will just default to localhost

    # Get the verion of opal
    echo "Opal version:"
    opal system --user administrator --password $OPAL_ADMINISTRATOR_PASSWORD --version

    # Add the NORMAL DEMO_USER as defined in the values.yaml
    opal user --user administrator --password $OPAL_ADMINISTRATOR_PASSWORD --add --name {{ .Values.opal.demo.userName }} --upassword $OPAL_DEMO_USER_PASSWORD
    
    ###########################################################################
    # CNSIM DEMO DATA
    ###########################################################################

    # Add a project
    opal project --user administrator --password $OPAL_ADMINISTRATOR_PASSWORD --add --name {{ .Values.opal.demo.projectName }} --database mongodb

    # Add the CNSIM1 data to the project
    cd /tmp
    mkdir opal-config-temp
    cd opal-config-temp
    wget {{ .Values.opal.demo.sourceDataUrl }}

    opal_fs_path="/home/administrator"
    opal_file_path="$opal_fs_path/`basename {{ .Values.opal.demo.sourceDataUrl }}`"

    opal file --user administrator --password $OPAL_ADMINISTRATOR_PASSWORD -up `basename {{ .Values.opal.demo.sourceDataUrl }}` $opal_fs_path

    opal import-csv --user administrator --password $OPAL_ADMINISTRATOR_PASSWORD --destination {{ .Values.opal.demo.projectName }} --path $opal_file_path  --tables {{ .Values.opal.demo.tableName }} --separator , --type Participant --valueType decimal
    
    touch /finished_local_customisation.txt
{{- end }}