apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    io.kompose.service: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongo
  strategy: {}
  template:
    metadata:
      annotations: {}
      labels:
        io.kompose.service: mongo
    spec:
      containers:
        - image: mongo:6.0
          name: mongo
          resources: {}
          volumeMounts:
          - name: "mongo-data-dir"
            mountPath: "/data/db"
      volumes:
      - name: "mongo-data-dir"
        persistentVolumeClaim:
          claimName: "mongo-storage-claim-1"
