apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  labels:
    name: mongo-service
    environment: {{ .Values.environment }}
spec:
  ports:
    - name: tcp
      port: 27017    
      targetPort: 27017
  selector:
    app: mongo-deployment
