apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    name: mongo-deployment
    environment: {{ .Values.environment }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-deployment
  strategy: {}
  template:
    metadata:
      labels:
        app: mongo-deployment
        environment: {{ .Values.environment }}
    spec:
      containers:
        - image: mongo:6.0
          name: mongo
          resources: {}
          volumeMounts:
          - name: "mongo-data-dir"
            mountPath: "/data/db"
      volumes:
      - name: "mongo-data-dir"
        persistentVolumeClaim:
          claimName: "mongo-storage-claim-1"
