apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-storage-claim-1
  labels:
    name: mysql-storage-1
    environment: {{ .Values.environment }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: mysql-storage-volume-1
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: manual
