apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: mysql-storage-1
  name: mysql-storage-claim-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: mysql-storage-volume-1
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: manual
