apiVersion: v1
kind: PersistentVolume
metadata:
  name: opal-storage-volume-1
  labels:
    io.kompose.service: opal-storage-1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/k8s/pvs/opal1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-storage-volume-1
  labels:
    io.kompose.service: mysql-storage-1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/k8s/pvs/mysql1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-storage-volume-1
  labels:
    io.kompose.service: mongo-storage-1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain

  storageClassName: manual
  hostPath:
    path: "/k8s/pvs/mongo1"