apiVersion: v1
kind: Service
metadata:
  #annotations:
  #  service.beta.kubernetes.io/azure-load-balancer-ipv4: 172.18.16.233
  #  service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
    io.kompose.service: opal
    service: ds-opal
  name: ds-opal
spec:
  #type: LoadBalancer
  type: NodePort
  ports:
    - name: http
      port: 80    
      targetPort: 8080
      nodePort: 30080
    - name: https
      port: 443
      targetPort: 8443
      nodePort: 30443
  selector:
    io.kompose.service: opal
