apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f opal-docker-compose.yaml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: opal
  name: opal
spec:
  ports:
    - name: "8880"
      port: 8880
      targetPort: 8080
  selector:
    io.kompose.service: opal
status:
  loadBalancer: {}
