apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    io.kompose.service: opal
  name: opal
spec:
  ports:
    - name: "8880"
      port: 8880
      targetPort: 8080
  selector:
    io.kompose.service: opal
status:
  loadBalancer: {}
