apiVersion: v1
kind: Service
metadata:
  name: opal-service
  labels:
    name: opal-service
    environment: {{ .Values.environment }}
spec:
  #type: LoadBalancer
  type: NodePort
  ports:
    - name: http
      port: 80    
      targetPort: 8080
      nodePort: 30080
    - name: https
      port: 443
      targetPort: 8443
      nodePort: 30443
  selector:
    app: opal-deployment
