apiVersion: v1
kind: Service
metadata:
  name: rock-service
  labels:
    name: rock-service
    environment: {{ .Values.environment }}
    context: {{ .Values.context }}
spec:
  ports:
    - name: tcp
      port: 8085    
      targetPort: 8085
  selector:
    app: rock-deployment
